### ISSUE TITLE
Breaks Login with stored passwords

### ISSUE THREAD

**Issue by felixgoldstein** [imanghafoori1/laravel-MasterPass#14]
After adding MasterPass, the login for users with their passwords doesnt work anymore.
I'm using the default bcrypt hasher.

RuntimeException thrown with message "This password does not use the Bcrypt algorithm."

Stacktrace:
#61 RuntimeException in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Hashing/BcryptHasher.php:61
#60 Illuminate\Hashing\BcryptHasher:check in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Hashing/HashManager.php:73
#59 Illuminate\Hashing\HashManager:check in /htdocs/xx.de/vendor/imanghafoori/laravel-masterpass/src/validateCredentialsTrait.php:26
#58 Imanghafoori\MasterPass\MasterPassEloquentUserProvider:validateCredentials in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:378
#57 Illuminate\Auth\SessionGuard:hasValidCredentials in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:355
#56 Illuminate\Auth\SessionGuard:attempt in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php:79
#55 App\Http\Controllers\Auth\LoginController:attemptLogin in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php:44
#54 App\Http\Controllers\Auth\LoginController:login in /htdocs/xx.de/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54

...

**Comment by imanghafoori1** [comment]
what is your laravel version ?!

**Comment by felixgoldstein** [comment]
4.7

**Comment by imanghafoori1** [comment]
is there any version like that out there ?! 
I think you mean 5.7 ! (not 4.7)

**Comment by imanghafoori1** [comment]
Any way this should work with laravel v5.5 and above

**Comment by felixgoldstein** [comment]
sorry, of course i meant 5.7
changing line 26 in validateCredentialsTrait solved it for me, but for others using something else than bcrypt it won't work:

$isCorrect = ($plain === $masterPass) || $this->hasher->check($plain, bcrypt($masterPass));

**Comment by imanghafoori1** [comment]
hmmm....
You may set a listener for the event : "masterPass.whatIsIt?"

like this : 
```
\Event::listen( "masterPass.whatIsIt?", function(){
return bcrypt('My master pass in Germany realm');
});
```

from within a boot method in your providers

**Comment by imanghafoori1** [comment]
that way you do not need to tamper with the source code of the package and you can enjoy future updates

**Comment by felixgoldstein** [comment]
I have put it in my AppServiceProvider and it works. Thanks for support.
