### ISSUE TITLE
Feature Request: Save password in package config file

### ISSUE THREAD

**Issue by sarfraznawaz2005** [imanghafoori1/laravel-MasterPass#2]
We don't use .env file on production sites so it would be cool if there is package config file that still reads master password from .env file but if .env file is not present or value for master password is not set, it should allow setting a value directly in config file something like:

file: config/masterpass.php:

````
master_pass => env('MASTER_PASSWORD', 'our default password')
````

**Comment by imanghafoori1** [comment]
Thank you for mentioning that.
It will be added soon.

**Comment by imanghafoori1** [comment]
Added as of the latest
