### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by mikkellindblom** [imanghafoori1/laravel-MasterPass#22]
Hey Iman!

Thanks for a nice package :) Will you add Laravel 6 support in near future?

**Comment by imanghafoori1** [comment]
Yeah, of course.
Also feel free to open up a pull request if you wanted to. ;)

**Comment by imanghafoori1** [comment]
Could you please install dev-master version to see if it works ?

**Comment by mikkellindblom** [comment]
Works from here :)

**Comment by imanghafoori1** [comment]
Ok, I publish a new version to be installable on version 6.0

**Comment by mikkellindblom** [comment]
Thanks! :)
