### ISSUE TITLE
Tag release for Laravel 7

### ISSUE THREAD

**Issue by cihantas** [imanghafoori1/laravel-MasterPass#26]
I can see support for Laravel 7 has been added in the `composer.json`, but not yet tagged. Would you be so kind to tag it/release it.

**Comment by imanghafoori1** [comment]
Hope you enjoy it.

**Comment by josegus** [comment]
it is working for laravel 7.1? I tried to install it for laravel 7.1 but thrown composer compatibility issues

**Comment by imanghafoori1** [comment]
Hmmm,  could you please provide an screen shot of the error message?
I do not see any reason to fail.

**Comment by cihantas** [comment]
Issue should be reopened. You haven't tagged a new release yet.

**Comment by josegus** [comment]
@imanghafoori1 here it is:

![image](https://user-images.githubusercontent.com/13947849/76969520-de607000-6900-11ea-9fef-5f77204b9610.png)

**Comment by imanghafoori1** [comment]
let me just carefully read it.
please open up a pull request if you have solution for that.
it would be welcome.

**Comment by imanghafoori1** [comment]
try it again.
the version 2.0.8 should be available.
Sorry I have too many packages these days to tag and release. So I wonder which one is which.
Good luck

**Comment by josegus** [comment]
![image](https://user-images.githubusercontent.com/13947849/76995308-0f06d080-6926-11ea-94c3-e362f313cbfc.png)

It is working now, thanks @imanghafoori1

**Comment by imanghafoori1** [comment]
Enjoy it.
