### ISSUE TITLE
Auth/RequestGuard::isLoggedInByMasterPass does not exist

### ISSUE THREAD

**Issue by rmundel** [imanghafoori1/laravel-MasterPass#28]
Everything seems to work fine except for the Auth::isLoggedInByMasterPass();

"message": "Method Illuminate\\Auth\\RequestGuard::isLoggedInByMasterPass does not exist.",
    "exception": "BadMethodCallException"

I'm on Laravel 6.18.3 using passport.

**Comment by imanghafoori1** [comment]
hhhmmm, is this issue still an issue?

**Comment by rmundel** [comment]
Yes

**Comment by imanghafoori1** [comment]
Are you calling it in a Service Provider?
or it is in a blade file or something ?

**Comment by imanghafoori1** [comment]
close due to inactivity.
