### ISSUE TITLE
[bug] doesn’t work with config caching

### ISSUE THREAD

**Issue by OwenMelbz** [imanghafoori1/laravel-MasterPass#3]
Hey :)

Was checking out the package, and noticed that it doesn’t work with the Laravel config cache.

This is because you access the “env” helper directly.

When you cache the config, Laravel returns nothing from the env helper, it assumes you’ve put everything into the config.

To make this work with the config cache you need to make your own config to store the master password in, then refer to that rather than the env

👍🏼

**Comment by imanghafoori1** [comment]
Thank for reporting the issue.
Could you please check the dev-master version ?

**Comment by imanghafoori1** [comment]
fixed as of version 1.1.0
