### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by salmanrajz** [imanghafoori1/laravel-MasterPass#38]
Sorry for raising issue? but it's not working after installing on Laravel 8 JetStream, Please help

**Comment by anhofmann** [comment]
I have the same problem.

**Comment by imanghafoori1** [comment]
hhhmmm...
I have never used jetstream, but I can guess the problem.

**Comment by salmanrajz** [comment]
so no solution yet?

**Comment by imanghafoori1** [comment]
try to add the maspter pass as the very last service provider in app.php to see what happens

**Comment by imanghafoori1** [comment]
The main problem is within the fortify package and there is nothing I can do from here.
I fixed it there. so I am closing the issue here.

https://github.com/laravel/fortify/pull/248
