### ISSUE TITLE
Not available install at Laravel 11.

### ISSUE THREAD

**Issue by Eoss01** [imanghafoori1/laravel-MasterPass#52]
Problem 1
    - imanghafoori/laravel-masterpass[v1.0.0, ..., v1.1.6, v2.0.0, ..., v2.0.1] require laravel/framework ~5.3 -> found laravel/framework[v5.3.0, ..., v5.8.38] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass[v2.0.2, ..., v2.0.6] require laravel/framework ^5.5 -> found laravel/framework[v5.5.0, ..., v5.8.38] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass v2.0.7 requires laravel/framework ^5.5|^6.0 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass v2.0.8 requires laravel/framework ^5.5|^6.0|^7.0 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass[v1.1.7, v2.0.9] require laravel/framework ^5.5|^6.0|^7.0|^8.0 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass v2.0.10 requires laravel/framework ^5.5|^6.0|^7.0|^8.0|^9.0 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass v2.2.28 requires laravel/framework ~5.1|6.*|7.*|8.*|9.*|10.* -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.12] but it conflicts with your root composer.json require (^11.9).
    - imanghafoori/laravel-masterpass[v2.2.48, ..., v2.2.49] require laravel/framework ^5.5|^6.0|^7.0|^8.0|^9.0|^10.0 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.12] but it conflicts with your root composer.json require (^11.9).
    - Root composer.json requires imanghafoori/laravel-masterpass * -> satisfiable by imanghafoori/laravel-masterpass[v1.0.0, ..., v1.1.7, v2.0.0, ..., v2.2.49].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require imanghafoori/laravel-masterpass:*" to figure out if any version is installable, or "composer require imanghafoori/laravel-masterpass:^2.1" if you know which you need.

**Comment by imanghafoori1** [comment]
I think you should run with `composer update -W` (with `-W`)
