### ISSUE TITLE
Hy! The publish command, do not published the config/master_password.php file

### ISSUE THREAD

**Issue by tnatanael** [imanghafoori1/laravel-MasterPass#6]
Hy!

As the title says...

My laravel version 5.4

**Comment by imanghafoori1** [comment]
Is the `config/master_password.php` already published ?!

**Comment by tnatanael** [comment]
To work i created it manually

the command:

php artisan vendor:publish --tag=master_password

do not created it...

**Comment by imanghafoori1** [comment]
I think it is because the service provider was not registered at the time you issued the command.

**Comment by imanghafoori1** [comment]
Happy to see your name in the package contributors.

**Comment by tnatanael** [comment]
Tks man!


Att.

Thiago Natanael

________________________________
De: Iman <notifications@github.com>
Enviado: terça-feira, 15 de janeiro de 2019 18:25
Para: imanghafoori1/laravel-MasterPass
Cc: Thiago Natanael; Mention
Assunto: Re: [imanghafoori1/laravel-MasterPass] Hy! The publish command, do not published the config/master_password.php file (#6)


@tnatanael<https://github.com/tnatanael> You can now upgrade it
